# Generated by Django 3.2.6 on 2023-02-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='home.user'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='business_unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='documentations', to='home.BusinessUnit'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='documentations', to='home.Tag'),
        ),
    ]
